version: "3.9"
services:
  # postgres:
  #   container_name: db
  #   image: "postgres:15.5"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
  #     timeout: 45s
  #     interval: 10s
  #     retries: 10
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #     - ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: keycloak
  #     POSTGRES_HOST: postgres
  #   networks:
  #     - local
  #   ports:
  #     - "5432:5432"

  keycloak:
    container_name: keycloak
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 22.0.4
    command: ["start", "--optimized"]
    env_file:
      - .env.keycloak
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres_data:
