server:
  port: 5000

spring:
  application:
    name: insight
  datasource:
    url: jdbc:postgresql://localhost:5432/insight?ApplicationName=INSIGHT_BACKEND_SERVICE&assumeMinServerVersion=9.0
    username: postgres
    password: mLmbBZf93xg0YwTpESHjofGA8DC5CmWI
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none # NERVER USE THIS
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
